config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'


  resources :campaigns do
    member do
      get 'edit_content_iframe' => 'campaigns#edit_content_iframe'
      get 'edit_content' => 'campaigns#edit_content'
      patch 'update_content' => 'campaigns#update_content'
      patch 'send_preview' => 'campaigns#send_preview'
      get 'send' => 'campaigns#send_campaign'
      get 'queue'
      get 'get_feed' => 'campaigns#get_feed'
      get 'webview'   => 'campaigns#webview'
    end
  end

  resources :subscriptions do
    post :create, as: 'subscribe'
    member do
      get 'unsubscribe'
      get 'subscribe'
      get 'confirm'
    end
  end

  resources :mailing_lists do
    member do
      match 'import', via: [:patch, :get]
    end
  end

  resources :templates


  post 'bounces' => 'deliveries#bounce'
  post 'deliveries' => 'deliveries#delivered'
  post 'complaints' => 'deliveries#complaint'
  get  'opened' => 'deliveries#opened'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'campaigns#index'
end

app/models/mailing_list.rb
class MailingList < Smailer::Models::MailingList

  has_and_belongs_to_many :subscriptions, -> { uniq }
  has_many :campaigns, inverse_of: :mailing_list, dependent: :destroy
  attr_accessor :csv_file

  def subscribers
    active_subscriptions
  end

  def active_subscriptions
    subscriptions.subscribed.confirmed
  end

  def guess_csv_columns(f)

    mapping = {}

    SmarterCSV.process(f, {
      :chunk_size => 1
    }) do |rows|
      rows.each do |row|

        row.keys.each do |key|
          res = Heuristics.test(key, :column_tester)
          case res
            when :name_key
              mapping[key] = :name
            when :email_key
              mapping[key] = :email
            when :created_at_key
              mapping[key] = :created_at
          end
        end
      end

      break #just look at one chunk
    end

    return mapping
  end

  def import(file)
    path = file.path

    f =  File.open(path,  "r:bom|utf-8")
    key_mapping = guess_csv_columns(f)
    f.close

    unless key_mapping.values.include?(:email)
      return {status: :error, message: "Could not find an e-mail column in the CSV file."}
    end

    f =  File.open(path,  "r:bom|utf-8")

    begin
      n = SmarterCSV.process(f, {
        chunk_size: 100,
        key_mapping: key_mapping
        }) do |rows|

          next unless rows.first.keys.include?(:email)

          self.delay.import_rows(rows)
      end
      f.close
      {status: :ok, key_mapping: key_mapping}
    rescue CSV::MalformedCSVError
      {status: :error, message: "Error importing file: #{$!.to_s}"}
    end


  end

  def import_rows(rows)
    rows.each do |row|
      self.delay.import_row(row)
    end
  end

  def import_row(row)
    email = row[:email]
    name  = row[:name]

    sub = Subscription.find_or_initialize_by(email: email)
    sub.created_at = DateTime.parse(row[:created_at]) if row[:created_at]
    sub.name       = name
    sub.importing  = true
    if sub.new_record?
      sub.confirmed  ||= true
      sub.subscribed ||= true
    end
    sub.save
    #don't send confirmation e-mail!!

    self.subscriptions << sub
  end

end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController
  load_and_authorize_resource
  skip_load_resource :only => [:create]

  # GET /mailing_lists
  def index
    @mailing_lists = MailingList.all
  end

  # GET /mailing_lists/1
  def show
    @subscriptions = @mailing_list.subscriptions.page(params[:page]).per(params[:per]||10)

    respond_to do |format|
      format.html
      format.json {
        period = params[:period] || 12

        active_scope = @mailing_list.active_subscriptions
        active_sum = active_scope.where("created_at < ?", period.weeks.ago ).count

        unsubscribed_scope = @mailing_list.subscriptions.where(subscribed: false)

        render json: [
            {name: "Active", data: active_scope.group_by_week(:created_at, last: period).count.map { |x,y| { x => (active_sum += y)} }.reduce({}, :merge)},
            {name: "Unsubscribed", data: unsubscribed_scope.group_by_week(:updated_at, last: period).count }
          ]

      }
    end
  end

  # GET /mailing_lists/new
  def new
    @mailing_list = MailingList.new
  end

  def import
    if request.patch?
      res = @mailing_list.import(params[:mailing_list][:csv_file])

      if res[:status].eql?(:error)
        flash[:error] = res[:message]
      else
        redirect_to @mailing_list, :notice => "Subscribers are importing"
      end
    end
  end

  # GET /mailing_lists/1/edit
  def edit
  end

  # POST /mailing_lists
  def create
    @mailing_list = MailingList.new(mailing_list_params)

    if @mailing_list.save
      redirect_to @mailing_list, notice: 'Mailing list was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /mailing_lists/1
  def update
    if @mailing_list.update(mailing_list_params)
      redirect_to @mailing_list, notice: 'Mailing list was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /mailing_lists/1
  def destroy
    @mailing_list.destroy
    redirect_to mailing_lists_url, notice: 'Mailing list was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailing_list
      @mailing_list = MailingList.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mailing_list_params
      params[:mailing_list].permit(:name)
    end
end

app/helpers/mailing_lists_helper.rb
module MailingListsHelper
end

app/views/mailing_lists/_form.html.haml
= simple_form_for(@mailing_list) do |f|
  = f.error_notification

  .form-inputs
    =f.input :name
    =f.input :google_analytics_id

  .form-actions
    = f.button :submit

app/views/mailing_lists/edit.html.haml
%h1 Editing mailing_list

= render 'form'

= link_to 'Show', @mailing_list
\|
= link_to 'Back', mailing_lists_path

app/views/mailing_lists/import.html.haml
%h1 #{@mailing_list.name} - Import Subscribers

= simple_form_for(@mailing_list, url: import_mailing_list_path(@mailing_list)) do |f|
  = f.error_notification

  .form-inputs
    =f.input :csv_file, as: :file

  .form-actions
    = f.button :submit

app/views/mailing_lists/index.html.haml
%h1 Mailing Lists

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Subscribers
      %th

  %tbody

    - @mailing_lists.each do |mailing_list|
      %tr
        %td= mailing_list.name
        %td= mailing_list.subscriptions.count
        %td
          .btn-group
            = link_to 'Show', mailing_list, class: 'btn btn-default'
            -if can? :destroy, mailing_list
              = link_to 'Destroy', mailing_list, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

%br

= link_to 'New Mailing list', new_mailing_list_path

app/views/mailing_lists/new.html.haml
%h1 New mailing_list

= render 'form'

= link_to 'Back', mailing_lists_path

app/views/mailing_lists/show.html.haml
%h1=@mailing_list.name

.btn-group
  = link_to 'Edit', edit_mailing_list_path(@mailing_list), class: 'btn btn-default'
  = link_to 'Import Subscribers', import_mailing_list_path(@mailing_list), class: 'btn btn-default'
  = link_to 'Back', mailing_lists_path, class: 'btn btn-default'


#opens-chart
  = line_chart mailing_list_path(@mailing_list, format: :json), library: {title: 'Subscribers over time'}



%table.table.table-striped
  %thead
    %tr
      %th Name
      %th E-mail
      %th Status

  %tbody

    - @subscriptions.each do |sub|
      %tr
        %td
          = sub.name
        %td= sub.email
        %td
          =sub.subscribed? ? 'Subscribed' : 'Unsubscribed'
          %br
          =sub.confirmed? ? 'Confirmed' : 'Unconfirmed'

.row
  .col-md-12
    = paginate @subscriptions, theme: 'twitter-bootstrap-3'