config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'


  resources :campaigns do
    member do
      get 'edit_content_iframe' => 'campaigns#edit_content_iframe'
      get 'edit_content' => 'campaigns#edit_content'
      patch 'update_content' => 'campaigns#update_content'
      patch 'send_preview' => 'campaigns#send_preview'
      get 'send' => 'campaigns#send_campaign'
      get 'queue'
      get 'get_feed' => 'campaigns#get_feed'
      get 'webview'   => 'campaigns#webview'
    end
  end

  resources :subscriptions do
    post :create, as: 'subscribe'
    member do
      get 'unsubscribe'
      get 'subscribe'
      get 'confirm'
    end
  end

  resources :mailing_lists do
    member do
      match 'import', via: [:patch, :get]
    end
  end

  resources :templates


  post 'bounces' => 'deliveries#bounce'
  post 'deliveries' => 'deliveries#delivered'
  post 'complaints' => 'deliveries#complaint'
  get  'opened' => 'deliveries#opened'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'campaigns#index'
end

app/models/campaign.rb
require 'uri'

module Smailer
  module Models
    class MailCampaign < ActiveRecord::Base

      def body_html
        #get the Campaign
        campaign = Campaign.find(self.id)
        campaign.body_html
      end

    end
  end
end


class Campaign < Smailer::Models::MailCampaign
  include AASM

  belongs_to :mailing_list, inverse_of: :campaigns
  belongs_to :template
  serialize :content_json, JSON

  attr_accessor :preview_recipients

  before_save do
    if self.content_json_changed? && self.content_json_was.blank?
      self.draft
    end
  end

  aasm :whiny_transitions => false do
    state :created, :initial => true
    state :drafted
    state :queueing
    state :queued
    state :sending
    state :sent

    event :draft do
      transitions :from => [:drafted, :created, :queued], :to => :drafted
    end

    event :queue do
      transitions :from => :drafted, :to => :queueing
      after do
        self.delay.create_queued_mails
      end
    end

    event :queued do
      transitions :from => :queueing, :to => :queued
      after do
        notify_admin_of_state_change
      end
    end

    event :send_campaign do
      transitions :from => :queued, :to => :sending
      after do
        self.enqueue_campaign_workers
      end
    end

    event :sent do
      transitions :from => :sending, :to => :sent
    end
  end

  def deliveries
    finished_mails
  end

  def state
    aasm_state
  end

  def create_queued_mails
    batch_size = Setting.get_with_default('queue.batch_size', 100).to_f

    self.subscribers.find_each(batch_size: batch_size) do |subscription|
      QueuedMailCreator.perform_async(self.id, subscription.email)
    end

    self.check_if_queued
  end

  def check_if_queued
    if self.queued? || self.queued_mails.count.eql?(self.subscribers.count)
      self.queued!
    else
      self.delay_for(Setting.get_with_default('queue.checkup_delay', 300).to_i.seconds).check_if_queued
    end
  end


  def enqueue_campaign_workers
    qm_count = self.queued_mails.count

    unless qm_count.zero?
      batch_size = Setting.get_with_default('queue.batch_size', 100).to_f
      worker_count = (qm_count/batch_size).ceil

      logger.debug "Run #{worker_count} workers: \n"

      worker_count.times do |i|
        logger.debug "\n -------- Worker #{i} --------"
        limit = batch_size
        CampaignWorker.perform_async(self.id, limit)
        sleep(1) #avoid race conditions
      end
    end
  end

  def templated_body_html
    return unless self.template
    if self.content_json.blank?
      return read_attribute(:body_html)
    end

    string = self.template.html

    html_doc = Nokogiri::HTML(string)
    html_doc.encoding = 'UTF-8'

    hash = JSON.parse(self.content_json)
    hash.each do |key, value|
      html_doc.at_css("##{key}").inner_html = value
    end

    html_string = html_doc.to_s
    inlined_string = Premailer.new(html_string,  warn_level: Premailer::Warnings::SAFE, with_html_string: true).to_inline_css

    #nokogiri/premailer tries to escape our interpolations. put them back
    inlined_string = inlined_string.gsub(/\%\%7B(.*?)\%7D/, '%{\1}')

    inlined_string = add_ga_tracking(inlined_string)

    inlined_string = add_custom_interpolations(inlined_string)

    inlined_string
  end

  def body_html
    templated_body_html
  end

  def add_custom_interpolations(text)
    return text if text.nil?

    datetime = DateTime.now
    {
      currentdayname:         lambda { datetime.strftime("%a") },
      currentday:             lambda { datetime.strftime("%-d") },
      currentmonthname:       lambda { datetime.strftime("%B") },
      currentyear:            lambda { datetime.strftime("%Y") },
      unsubscribe:            lambda { "<a href=\"http://#{ENV['MAIL_HOST']}/subscriptions/%{email_key}/unsubscribe\">unsubscribe</a>" },
      webversion:             lambda { "<a href=\"http://#{ENV['MAIL_HOST']}/campaigns/%{message_key}/webview\">View web version</a>" }
    }.each do |variable, interpolation|
      text.gsub! "%{#{variable}}" do
        interpolation.respond_to?(:call) ? interpolation.call : interpolation.to_s.html_safe
      end
    end

    text
  end

  def add_ga_tracking(html)
    # add tracking pixel
    px_url = "https://#{ENV['MAIL_HOST']}/opened?key=%{message_key}'"
    html = html.gsub("</body>", "<style>@media print{ #_t { background-image: url('#{px_url}');}} div.OutlookMessageHeader {background-image:url('#{px_url}')} table.moz-email-headers-table {background-image:url('#{px_url}')} blockquote #_t {background-image:url('#{px_url}')} #MailContainerBody #_t {background-image:url('#{px_url}')}</style><div id='_t'></div><img src='#{px_url}' width='1' height='1' border='0' /></body>")
    # <img src='https://#{ENV['MAIL_HOST']}/opened?key=%{message_key}' >")

    # add utm_params to links
    html = html.gsub(/href=[\'\"](.*?)[\'\"]/){|match|
      begin
        uri = URI.parse($1)
        ga = {
          source: "Newsletter",
          medium: "email",
          campaign: subject
        }

        params = []
        ga.each {|key, value|
          (params += (URI.decode_www_form(uri.query || "") << ["utm_#{key}", value])).inspect
        }

        uri.query = URI.encode_www_form(params)

        match.sub($1, uri.to_s)
      rescue URI::InvalidURIError
        match
      end
    }

    html
  end

  def send_preview
    campaign = self
    return if campaign.preview_recipients.blank?

    rails_delivery_method = if Smailer::Compatibility.rails_3_or_4?
      method = Rails.configuration.action_mailer.delivery_method
      [ActionMailer::Base.delivery_methods[method], ActionMailer::Base.send("#{method}_settings")]
    else
      [ActionMailer::Base.delivery_method]
    end

    Mail.defaults do
      delivery_method *rails_delivery_method
    end

    self.preview_recipients.split(',').each do |address|
      qm = QueuedMail.new
      qm.mail_campaign = self
      qm.to = address

      html_body = qm.body_html

      mail = Mail.new do
        from    campaign.from
        to      address
        subject "#{Setting.get_with_default("campaign.preview_subject_prefix", "[PREVIEW]")} #{campaign.subject}"

        text_part { body campaign.body_text }
        html_part { body html_body; content_type 'text/html; charset=UTF-8' }
      end
      mail.raise_delivery_errors = true
      mail.deliver
    end
  end

  def body_text_from_json
    return "" if content_json.blank?
    html = ""

    JSON.parse(content_json).each do |key, value|
      html << value
    end

    HtmlToPlainText.plain_text(html)
  end


  def last_feed_used
    mailing_list.feed
  end

  def subscribers
    mailing_list.subscribers
  end

  def unopened_count
    subscribers.count - opened_mails_count
  end

  def complaints_count
    deliveries.sum(:complaints_count)
  end

  def bounces_count
    deliveries.sum(:bounces_count)
  end

  def hit_rate
    return nil if deliveries.count == 0
    opened_mails_count.to_f / deliveries.count
  end


  def notify_admin_of_state_change
    UserMailer.delay.campaign_notification(self)
  end


end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:webview]
  skip_before_action :authenticate_user!, :only => [:webview]
  skip_authorization_check :only => [:webview]

  skip_load_resource :only => [:create, :webview]


  # GET /campaigns
  def index
    @campaigns = Campaign.order('created_at DESC').page(params[:page]).per(params[:per]||10)
  end

  # GET /campaigns/1
  def show
    respond_to do |format|
      format.html
      format.json {
        opened = @campaign.deliveries.where(opened: true)
        bounced = @campaign.deliveries.where("bounced_at IS NOT NULL")

        render json: [
            {name: "Opened", data: opened.group_by_hour(:opened_at).count}
          ]

      }
    end
  end

  def webview
    @delivery = Delivery.where(key: params[:id]).first
    @campaign = Campaign.find(@delivery.mail_campaign)
    render text: @campaign.body_html, layout: false
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  def get_feed
    if url = params[:url]
      @campaign.mailing_list.update_attribute(:feed, url)
      @feed = Feedjira::Feed.fetch_and_parse(url)
    end
    render layout: false
  end

  def edit_content_iframe
    @template_content = @campaign.template.html
    render layout: 'edit_email_content'
  end

  def edit_content
  end

  def update_content
    @campaign.update(campaign_params)

    redirect_to edit_content_campaign_path(@campaign), notice: 'Saved'
  end

  def send_preview
    @campaign.preview_recipients = params[:campaign][:preview_recipients]

    unless @campaign.preview_recipients.blank?
      @campaign.send_preview
      flash[:notice] = 'Preview sent'
    else
      flash[:notice] = 'No recipients provided'
    end

    redirect_to @campaign
  end



  # POST /campaigns
  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      redirect_to @campaign, notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /campaigns/1
  def update
    if @campaign.update(campaign_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /campaigns/1
  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end

  def queue
    @campaign.queue!
    redirect_to @campaign, notice: 'Campaign is queueing.'
  end

  def send_campaign
    @campaign.send_campaign!
    redirect_to @campaign, notice: 'Campaign is sending.'
  end


  private
    # Only allow a trusted parameter "white list" through.
    def campaign_params
      params[:campaign].permit(:from, :subject, :body_html, :body_text, :mailing_list_id, :template_id, :content_json)
    end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def entry_image(entry)
    if entry.image
      #add protocol to relative protocol images
      entry.image.starts_with?('//') ? "http:#{entry.image}" : entry.image
    else
      first_image(entry.summary)
    end
  end

  def first_image(html)
    doc = Nokogiri::HTML(html)
    if img = doc.at('img')
      img['src']
    else
      ''
    end
  end

end

app/views/campaigns/_form.html.haml
= simple_form_for(@campaign, html: { class: "form-horizontal"} ) do |f|
  = f.error_notification

  .row
    .col-md-4
      .form-inputs
        = f.input :subject

        = f.input :from, as: :select, collection: SenderAddress.all.map(&:email)
        = f.association :mailing_list, as: :select

        = f.association :template, as: :select

        .hidden
          = f.input :content_json

        -if @campaign.content_json
          =f.input :body_text, input_html: {value: strip_tags(@campaign.body_text_from_json) }

      .form-actions
        = f.button :submit, class: 'btn-primary'
        = link_to 'Cancel', campaigns_path, class: 'btn btn-default'

    -if @campaign.persisted?
      .col-md-8
        %iframe{src: edit_content_iframe_campaign_path(@campaign, editable: true), width: '100%', height: '1000px', style:"height: 1000px; width: 100%; ", frameborder:"0" }



-content_for :on_ready do
  :plain
    editor_iframe = $('iframe')[0];

    $(editor_iframe).load(function(){
      content_json = #{@campaign.content_json}

      editor = this.contentWindow.window.editor;

      editor.loadContents(content_json);

      textarea = $("#campaign_content_json")[0];
      editor.bindToTextArea(textarea);
    })

app/views/campaigns/edit.html.haml
%h1 Editing campaign

= simple_form_for(@campaign, html: { class: "form-horizontal"} ) do |f|
  = f.error_notification

  .row
    .col-md-4

      %a.btn.btn-default#loadFeedItems{data: {disable_with: 'Loading...'}}
        Fetch Feed Items
        -if @campaign.last_feed_used
          (#{@campaign.last_feed_used})

      #feed-placeholder

      .form-inputs
        = f.input :subject

        = f.input :from, as: :select, collection: SenderAddress.all.map(&:email)
        = f.association :mailing_list, as: :select

        = f.association :template, as: :select

        .hidden
          = f.input :content_json

        -if @campaign.content_json
          =f.input :body_text, input_html: {value: strip_tags(@campaign.body_text_from_json) }

      .form-actions
        = f.button :submit, class: 'btn-primary'
        = link_to 'Cancel', campaigns_path, class: 'btn btn-default'

    -if @campaign.persisted?
      .col-md-8
        %iframe{src: edit_content_iframe_campaign_path(@campaign, editable: true), width: '100%', height: '1000px', style:"height: 1000px; width: 100%; ", frameborder:"0" }

-content_for :on_ready do
  :plain

    $('#loadFeedItems').click(function(){
      url = prompt('Enter the feed URL', '#{@campaign.last_feed_used}');
        if (url != null){
        url = escape(url);
        link = $(this);
        $.get('#{get_feed_campaign_path(@campaign)}?url='+url, function(data){
          $('#feed-placeholder').html(data);

          link.html('Load Feed Items');
          link.off();
          link.click(function(){
            newHtml = $('.feed-preview').html();
            editor.replaceHTML(newHtml);
            $('#feed-placeholder').remove();
            link.remove();
          })

        })
      }
    })

    editor_iframe = $('iframe')[0];

    $(editor_iframe).load(function(){
      content_json = #{@campaign.content_json.blank? ? "{}" : @campaign.content_json};

      editor = this.contentWindow.window.editor;
      editor.loadContents(content_json);

      textarea = $("#campaign_content_json")[0];
      editor.bindToTextArea(textarea);

    })

app/views/campaigns/edit_content.html.haml
.row
  .col-md-2

    = simple_form_for(@campaign, :url => update_content_campaign_path(@campaign), html: {class: "form-horizontal"} ) do |f|
      = f.error_notification

      .form-inputs.hidden
        = f.input :content_json
      .form-actions

        = f.submit "Save", class: 'btn-primary btn'
        = link_to "Cancel", @campaign

  .col-md-10
    %iframe{src: edit_content_iframe_campaign_path(@campaign), width: '100%', height: '1000px', style:"height: 1000px; width: 100%; ", frameborder:"0" }


-content_for :on_ready do
  :plain
    editor_iframe = $('iframe')[0];

    $(editor_iframe).load(function(){
      content_json = #{@campaign.content_json}

      editor = this.contentWindow.window.editor;

      $(editor.elements).each(function(){
        //load the contents into the template
        $(this).html(content_json[$(this).attr('id')].value);

        //listen for changes and update the form
        $(this).on('input', function(){
          json_string = JSON.stringify(editor.serialize());
          $('#campaign_content_json').val(json_string);
        })
      })

    })

app/views/campaigns/edit_content_iframe.html.haml
#email_content
  =raw @template_content

-content_for :on_ready do
  :plain
    $(function() {
      window.editor = new Editor("#email_content .editable");
      window.editor.initCkeditor({readOnly: #{params[:editable].blank?}})
    });


  :plain
    $(function() {
      $('#email_content').click(function(e){
        if($(e.target).hasClass('editable')){
        } else {
          e.preventDefault();
          e.stopPropagation();
          return false;
        }
      })
    });

app/views/campaigns/get_feed.html.haml
-if @feed
  #feed.feed-preview
    -@feed.entries.each do |entry|
      %h2=link_to entry.title, entry.url
      %p
        %a{href: entry.url}
          = image_tag( entry_image(entry) )
        -if entry.summary
          = truncate(strip_tags(entry.summary), length: 200, omission: '...' )
        = link_to('READ MORE', entry.url)

app/views/campaigns/index.html.haml
%h1 Campaigns

%table.table.table-striped
  %thead
    %tr
      %td Date
      %th Name
      %th Subject
      %th Status
      %th

  %tbody
    - @campaigns.each do |campaign|
      %tr
        %td.col-md-1
          = campaign.created_at.to_s(:db)
        %td.col-md-2
          = campaign.name
        %td.col-md-2
          = campaign.subject
        %td.col-md-5
          = campaign.state.capitalize
          to #{campaign.mailing_list.active_subscriptions.count} recipients
          -case campaign.state
            -when 'sent'
              (#{number_to_percentage (campaign.hit_rate*100), precision: 2, strip_insignificant_zeros: true} opened)
            -when 'sending' || 'queued'
              (#{campaign.deliveries.count} delivered)
          -if campaign.sent? || campaign.sending?
            =link_to 'view stats', campaign_path(campaign)

        %td
          .btn-group
            = link_to 'Show', campaign, class: "btn btn-default"
            -if !campaign.sent?
              = link_to 'Edit', edit_campaign_path(campaign), class: "btn btn-default"
            -if can? :destroy, campaign
              = link_to 'Destroy', campaign, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

  = paginate @campaigns, theme: 'twitter-bootstrap-3'
%br

= link_to 'New Campaign', new_campaign_path

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

app/views/campaigns/show.html.haml
%h1= @campaign.name

-if @campaign.sent? || @campaign.sending?
  .row
    .col-md-9

      .panel.panel-default
        .panel-heading
          .panel-title
            =@campaign.subject
            -if @campaign.deliveries.any?
              .pull-right
                =link_to 'View', webview_campaign_path(@campaign.deliveries.last.key), target: '_blank'
          -if @campaign.deliveries.any?
            Sent on #{@campaign.deliveries.maximum(:sent_at).to_s(:long)}
          to #{@campaign.deliveries.count} unique subscribers in #{@campaign.mailing_list.name}

        .panel-body
          .row
            .col-md-9#opens-chart
              = line_chart campaign_path(@campaign, format: :json), library: {title: 'Opens over time'}


          .row
            .col-md-6
              %ul.list-unstyled
                %li
                  %h1 #{@campaign.opened_mails_count}
                  Opens so far
                %li
                  %h1 #{@campaign.unopened_count}
                  Not opened yet

            .col-md-3
              %ul.list-unstyled
                %li
                  %h1 #{number_to_percentage ((@campaign.hit_rate||0)*100), precision: 2, strip_insignificant_zeros: true}
                  Open rate
                %li
                  %h1 #{@campaign.complaints_count}
                  Complaints
          .row
            .col-md-3
              %ul.list-unstyled
                %li
                  %h1 #{@campaign.bounces_count}
                  Bounces

          .row
            %h1 Who Opened
            %table.table.table-striped
              %thead
                %tr
                  %th Who
                  %th Opened Count

              %tbody
                -@campaign.deliveries.where(opened: true).order('opens_count DESC').limit(50).each do |sub|
                  %tr
                    %td= sub.to
                    %td= sub.opens_count


-else
  .row
    .col-md-3
      .panel.panel-default
        .panel-heading
          Send a test campaign to...

        .panel-body
          = simple_form_for(@campaign, url: send_preview_campaign_path(@campaign), html: { class: "form"} ) do |f|
            =f.input :preview_recipients, hint: 'Enter e-mail addresses, separated by a comma'

            .form-actions
              =f.button :submit, "Send Preview Campaign"

      .btn-group
        -if @campaign.created? || @campaign.drafted?
          = link_to 'Edit Campaign', edit_campaign_path(@campaign), class: 'btn btn-primary'
          -if @campaign.drafted? && !@campaign.queueing?
            = link_to 'Queue', queue_campaign_path(@campaign), class: 'btn btn-warning', data: {confirm: "Queue this to #{@campaign.mailing_list.subscribers.count} subscribers?" }
        -elsif @campaign.queueing?
          =link_to 'Queuing ...', @campaign, class: 'btn btn-default'
        -elsif @campaign.queued?
          = link_to 'Send', send_campaign_path(@campaign), class: 'btn btn-danger', data: {confirm: "Send this to #{@campaign.mailing_list.subscribers.count} subscribers?" }

        = link_to 'Back', campaigns_path, class: 'btn btn-default'

    .col-md-9
      -if @campaign.content_json
        .panel.panel-default
          .panel-heading HTML E-mail
          .panel-body
            %iframe{src: edit_content_iframe_campaign_path(@campaign), width: '100%', height: '500px', style:"height: 500px; width: 100%; ", frameborder:"0" }

        .panel.panel-default
          .panel-heading Plain Text
          .panel-body
            %pre
              =@campaign.body_text

        -content_for :on_ready do
          :plain
            editor_iframe = $('iframe')[0];

            $(editor_iframe).load(function(){
              content_json = #{@campaign.content_json}

              editor = this.contentWindow.window.editor;

              editor.loadContents(content_json);
            })

app/views/campaigns/show.json.haml
=raw escape_javascript @campaign.deliveries.to_json